#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "$0")"

if ! command -v pdflatex >/dev/null 2>&1; then
  echo "pdflatex not found. Please install MacTeX/BasicTeX (e.g., 'brew install --cask mactex-no-gui')" >&2
  exit 1
fi

root_dir=".."

# Escape LaTeX special characters via sed
escape_caption() {
  printf '%s' "$1" | sed \
    -e 's/\\/\\\\textbackslash{}/g' \
    -e 's/_/\\\\_/g' \
    -e 's/%/\\\\%/g' \
    -e 's/&/\\\\&/g' \
    -e 's/#/\\\\#/g' \
    -e 's/\$/\\\\\$/g' \
    -e 's/{/\\\\{/g' \
    -e 's/}/\\\\}/g'
}

# Generate LaTeX figure grid for all solution images in chunks
gen_tex="generated_figures.tex"
{
  echo "% This file is auto-generated by build_performance_report.sh"
  echo "% It will be overwritten. Do not edit by hand."
  shopt -s nullglob
  imgs=( "$root_dir"/solution_*.png "$root_dir"/mf_*.png )
  total=${#imgs[@]}
  if (( total == 0 )); then
    echo "\\begin{figure}[h]"
    echo "  \\centering"
    echo "  \\fbox{No result figures found}"
    echo "  \\caption{All discovered result figures.}"
    echo "\\end{figure}"
  else
    count=0
    open_block=false
    for img in "${imgs[@]}"; do
      [ -e "$img" ] || continue
      base=$(basename "$img")
  cap=$(escape_caption "$base")
      # Open a new figure every 8 images
      if ! $open_block; then
        echo "\\begin{figure}[ht]"
        echo "  \\centering"
        open_block=true
      fi
      echo "  \\begin{subfigure}[b]{0.48\\textwidth}"
      echo "    \\centering"
      echo "    \\IfFileExists{$img}{\\includegraphics[width=\\linewidth]{$base}}{\\fbox{$cap\\ not found}}"
      echo "    \\caption{$cap}"
      echo "  \\end{subfigure}\\hfill"
      count=$((count+1))
      if (( count % 2 == 0 )); then
        echo "  "
      fi
      if (( count % 8 == 0 )); then
        echo "  \\caption{Result figures (batch $((count-7))--$count).}"
        echo "\\end{figure}"
        echo "\\clearpage"
        open_block=false
      fi
    done
    # Close final open block
    if $open_block; then
      echo "  \\caption{Result figures (batch $(( ( (count-1)/8 )*8 + 1 ))--$count).}"
      echo "\\end{figure}"
    fi
  fi
} > "$gen_tex"

# Generate residual plots and gallery
bash "$PWD/plot_residuals.sh" || true
res_dir="residuals"
res_tex="$res_dir/generated_residual_figures.tex"
mkdir -p "$res_dir"
{
  echo "% Auto-generated by build_performance_report.sh"
  echo "% Includes all residual plots found in docs/residuals/*_rel.png and *_L2.png."
  shopt -s nullglob
  rels=( "$res_dir"/*_rel.png )
  l2s=( "$res_dir"/*_L2.png )
  if (( ${#rels[@]} + ${#l2s[@]} == 0 )); then
    echo "% No residual plots found."
  else
    echo "\\begin{figure}[ht]"
    echo "  \\centering"
    count=0
    for img in "${rels[@]}" "${l2s[@]}"; do
      base=$(basename "$img")
      cap=$(escape_caption "$base")
      echo "  \\begin{subfigure}[b]{0.48\\textwidth}"
      echo "    \\centering"
      echo "    \\includegraphics[width=\\linewidth]{$img}"
      echo "    \\caption{$cap}"
      echo "  \\end{subfigure}\\hfill"
      count=$((count+1))
      if (( count % 2 == 0 )); then
        echo "  "
      fi
    done
    echo "  \\caption{Residual convergence plots (relative and L2).}"
    echo "\\end{figure}"
  fi
} > "$res_tex"

# Generate grouped (solution + residuals) results section
bash "$PWD/generate_grouped_results.sh" || true

pdflatex -interaction=nonstopmode performance_report.tex >/dev/null || true
pdflatex -interaction=nonstopmode performance_report.tex >/dev/null || true
if [ -f performance_report.pdf ]; then
  echo "Report generated: docs/performance_report.pdf"
  exit 0
else
  echo "Failed to generate report" >&2
  exit 1
fi
